### PR TITLE
Relax fmtp checking to better match RFC

### LINKED ISSUE #2: Relax checking of a=fmtp line ending
Currently the a=fmtp line is checked for a tailing `; `. This is only necessary because of an inclusion in ST.2110-10. Generic SDP files should not fail because of this, and as this requirement may be revised in ST.2110's one year review it seems unnecessary to penalise implementations for the error.

### PR DESCRIPTION
**Pull request by andrewbonney**
Resolves #2 

This is far more permissive in its fmtp checking, but still ensures that poorly formatted lines like the following fail:
```
a=fmtp:22 testparam=; anotherparam=fail
```

As there are some regex changes, it could do with a thorough review.

Also includes a couple of minor fixes, and some further example SDPs (modified from the NMOS testing tool ones) intended to aim with future work on #4

### CODE REVIEW

File: checkST2110.js [hunk 1]
```diff
@@ -51,15 +51,15 @@ a=recvonly
 a=group:DUP primary secondary
 m=video 50000 RTP/AVP 112
 c=IN IP4 239.100.9.10/32
-a=source-filter: incl IN IP4 239.100.9.10 192.168.100.2
+a=source-filter:incl IN IP4 239.100.9.10 192.168.100.2
```
Comment (garethsb-sony) [inline checkST2110.js]: I raised this in the ongoing review of ST 2110-10. I don't know whether it will be corrected or not.

Comment (andrewbonney) [reply checkST2110.js]: Yeah I think it will be, but given this specific file is intended to catch obvious copies of the file from the standard I probably shouldn't have 'corrected' it in the first place.

File: checkST2110.js [hunk 2]
```diff
@@ -28,8 +28,8 @@ const groupPattern = /a=group:DUP\s+(\S+)\s+(\S+)/;
 const ssrcPattern = /a=ssrc:(\d+)\s/;
 const videoPattern = /video\s+(\d+)(\/\d+)?\s+(RTP\/S?AVP)\s+(\d+)/;
 const rtpmapPattern = /a=rtpmap:(\d+)\s(\S+)\/(\d+)\s*/;
-const fmtpPattern = /a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s;]+))?;\s+)*$/;
-const fmtpParams = /([^\s=;]+(?:=[^\s;]+)?);/g;
+const fmtpPattern = /a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s;]+))*(?:;\s*)*)+$/;
```
Comment (garethsb-sony) [inline checkST2110.js]: Is this right? The `(?:;\s*)*` matches zero or many semi-colons... Oh, I guess the greedy matching of the previous terms means you can't actually have zero semi-colons anywhere but right at the end, and multiple semi-colon separators are perhaps allowed... OK...

Comment (andrewbonney) [reply checkST2110.js]: I don't see a problem with changing that to `(?:;\s*){0,1}`. Certainly a quick test shows that avoids `a=fmtp:79 foo=bar;;;;foo=bar` from passing.

File: checkST2110.js [hunk 3]
```diff
@@ -28,8 +28,8 @@ const groupPattern = /a=group:DUP\s+(\S+)\s+(\S+)/;
 const ssrcPattern = /a=ssrc:(\d+)\s/;
 const videoPattern = /video\s+(\d+)(\/\d+)?\s+(RTP\/S?AVP)\s+(\d+)/;
 const rtpmapPattern = /a=rtpmap:(\d+)\s(\S+)\/(\d+)\s*/;
-const fmtpPattern = /a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s;]+))?;\s+)*$/;
-const fmtpParams = /([^\s=;]+(?:=[^\s;]+)?);/g;
+const fmtpPattern = /a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s;]+))*(?:;\s*){0,1})+$/;
```
Comment (garethsb-sony) [inline checkST2110.js]: Should the `fmtpPattern` allow `a=fmtp:42 a=b=c=`? (It does right now.)

Should it allow `a=fmtp:42` alone, or `a=fmtp:42 `, with a trailing space? (It doesn't at the moment.)

Comment (andrewbonney) [reply checkST2110.js]: The latter is intentional, the former is not.

Comment (garethsb-sony) [reply checkST2110.js]: `a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s=;]+))?(?:;\s*){0,1})+$`
Maybe?

Comment (andrewbonney) [reply checkST2110.js]: I can't immediately find a reference which suggests it's invalid, although I certainly haven't seen it used like that before. Unfortunately the suggested fix doesn't appear to solve it. I'm having a play with alternatives, but perhaps if there's nothing to say it's invalid that's unnecessary.

Comment (garethsb-sony) [reply checkST2110.js]: Hm, works for me at https://regex101.com/

But yes, if a value containing `=` isn't invalid, so be it. Still would make sense to change the `*` to `?` though?

Comment (garethsb-sony) [reply checkST2110.js]: Conclusion via Slack chat was that the required regex is:
`a=fmtp:(\d+)\s+(?:([^\s=;]+)(?:=([^\s;]+))?)((?:;\s*)(?:([^\s=;]+)(?:=([^\s;]+))?))*(?:;\s*)?$`

This is made up of (in pseudo-code):

`fmtpElement` = `([^\s=;]+)(?:=([^\s;]+))?`

`fmtpSeparator` = `(?:;\s*)`

`fmtpPattern` = `a=fmtp:(\d+)\s+` `fmtpElement` + `(` `fmtpSeparator` + `fmtpElement` `)*` + `fmtpSeparator` `?$`

(I'm not sure whether you can build up regexes with string-like concatenation in Javascript?)
Obviously then the `fmtpParams` regex can also be built out of `fmtpElement` and `fmtpSeparator` too.

Comment (andrewbonney) [reply checkST2110.js]: I believe this is now reflected in the next commit.
